version: '3'
services:
  api:
    build: 
      context: ./helpdesk-api
      dockerfile: Dockerfile
    command: npm start
    ports:
      - '3333:3333'
  frontend:
    build: 
      context: ./helpdesk-front
      dockerfile: Dockerfile
    command: npm start
    ports:
      - '3334:3334' 

